name: app1
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  messaging_testing:
    path: ../packages/messaging_testing

  notification_testing:
    path: ../packages/notification_testing

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  built_value_generator: ^8.4.0
  http: ^0.12.0
  audioplayers:
    git:
      url: git@github.com:manabie-com/audioplayers.git
      path: packages/audioplayers

flutter:
  uses-material-design: true
