name: ci_cd_trainning
version: 1.0.0+1
description: Training CI/CD
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  pubspec_lock:
    path: ../pubspec_lock
  pubspec_yaml: ^3.1.0
  test: ^1.17.12

dependency_overrides:
  borg:
    path: ../dart-borg

flutter:
  uses-material-design: true
