name: messaging_testing
version: 0.0.1
description: A new Flutter package project.
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.12.0
  technical_1:
    path: ../technical_1
  technical_2:
    path: ../technical_2

dev_dependencies:
  built_value_generator: ^8.4.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  url_launcher: 6.0.0

flutter:
  uses-material-design: true
