name: notification_testing
description: A new Flutter package project.
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Testing ----------------------------
  http: ^0.12.0

  technical_1:
    path: ../technical_1

  technical_2:
    path: ../technical_2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  built_value_generator: ^8.4.0

dependency_overrides:
  url_launcher: 6.1.0

flutter:
  uses-material-design: true
