name: GitHub Actions Demo
on: [push]
jobs:
  example-job:
    name: Save output
    runs-on: ubuntu-lastest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  example-job-2:
    name: Get output
    runs-on: ubuntu-lastest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
