name: Test Context
on: [push]
jobs:
  Draft-Check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start check branch"
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - run: echo "Github context ${{github}}"
      - run: echo "Github context ${{github.ref}}"

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump GitHub context
        id: github_secrets_step
        run: echo '${{ toJSON(secrets) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - run: echo '${{ secrets.GITHUB_TOKEN }}'
      - run: echo '${{ github.token }}'
      # - run:
      #     if: ${{secrets.GITHUB_TOKEN == github.token}} echo "true"
