name: Testing expressions
on: [push]
jobs:
  Test-expressions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start testing expressions"
      - run: echo "${{join(['le', 'chi', 'nhin'], ' ')}}"