name: Test Context
on: [push]
jobs:
  Testing-Context:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start testing context"

  Draft-Check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start check branch"
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - run: echo "Github context ${{github}}"