name: Testing Build Android Application
env:
  FLUTTER_VERSION: "2.8.1"
on: [push]
jobs:
  Testing-Build-Android-App:
    runs-on: ubuntu-latest
    steps:
      # install flutter
      - run: echo "Start build android application"
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION
    
      # get flutter packages & run unit test
      - name: Run Tests With Makefile
        run: make run-test

      # start android simulator

      
      # build android application